networks:
  default: local-mainnet-fork
  Ganache-CLI: 
    id: local-mainnet-fork
    display_name: mainnet
    chainid: 1
    host: https://mainnet.infura.io/v3/c55d8ff021d14bcd87b9389c1fbb7cad
    explorer: https://api.etherscan.io/api
    multicall2: "0x5BA1e12693Dc8F9c48aAD8770482f4739bEeD696"
    provider: infura

compiler:
  solc:
    optimizer:
      enabled: true
      runs: 1000000

env_vars:
  WEB3_INFURA_PROJECT_ID: c55d8ff021d14bcd87b9389c1fbb7cad

remappings:
  - zeppelin=/usr/local/lib/open-zeppelin/contracts/
  - github.com/ethereum/dapp-bin/=/usr/local/lib/dapp-bin/
  - '@OpenZeppelin=OpenZeppelin/openzeppelin-contracts@3.0.0'
